export const card: string;
export const cardActions: string;
export const cardContent: string;
export const cardCookingTime: string;
export const cardInfo: string;
export const cardLink: string;
export const cardThumbnail: string;
export const cardThumbnailImage: string;
export const cardTitle: string;
